# Generated by Django 5.0.6 on 2024-06-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession_app', '0004_blogpost_confession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
