# Generated by Django 5.0.6 on 2024-06-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_app', '0005_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confession',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
