# Generated by Django 5.0.6 on 2024-06-08 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_app', '0006_confession_dislikes_confession_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='likes',
        ),
        migrations.AddField(
            model_name='confession',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_confessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confession',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_confessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
